<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentationPageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pages')
            ->insert([
                'created_at' => now(),
                'title'      => 'Documentation',
                'slug'       => 'docs',
                'blocks'     => json_encode([
                    [
                        'type' => 'component.heading-description',
                        'data' => [
                            'title'                    => 'Documentation',
                            'subtitle'                 => 'Welcome to the Warriorfolio documentation. This guide will help you understand the main features of the system and how to use them.',
                            'is_active'                => true,
                            'is_center'                => false,
                            'is_filled'                => false,
                            'with_padding'             => true,
                            'is_heading_visible'       => true,
                            'module_id'                => 'documentation',
                            'is_featured_image_active' => true,
                        ],
                    ],
                    [
                        'type' => 'component.feature-list',
                        'data' => [
                            'module_title'               => 'The 3 Concepts',
                            'module_subtitle'            => 'Warriorfolio is based on 3 main concepts that will help you understand how to use the system and how to create your own components.',
                            'columns'                    => '3',
                            'is_active'                  => true,
                            'is_center'                  => false,
                            'is_filled'                  => false,
                            'is_animated'                => false,
                            'is_light_fx'                => true,
                            'is_color_icon'              => false,
                            'is_card_filled'             => true,
                            'is_content_center'          => false,
                            'is_heading_active'          => false,
                            'is_filled_inverted'         => false,
                            'is_section_filled_inverted' => false,
                            'is_border'                  => true,
                            'with_padding'               => false,
                            'features'                   => [
                                [
                                    'icon'          => 'layers-outline',
                                    'title'         => 'Modularity',
                                    'description'   => 'Warriorfolio uses modular design for flexible, reusable portfolio components.',
                                    'link'          => '/admin',
                                    'is_new_window' => true,
                                ],
                                [
                                    'icon'          => 'cube-outline',
                                    'title'         => 'Components',
                                    'description'   => 'Reusable building blocks for creating flexible portfolio layouts.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'hardware-chip-outline',
                                    'title'         => 'Core Modules',
                                    'description'   => 'Pre-built components designed to accelerate page development.',
                                    'link'          => '/admin',
                                    'is_new_window' => true,
                                ],
                            ],
                        ],
                    ],
                    [
                        'type' => 'component.feature-list',
                        'data' => [
                            'module_title'               => 'Features',
                            'module_subtitle'            => 'Discover the features of Warriorfolio.',
                            'columns'                    => '4',
                            'is_active'                  => true,
                            'is_center'                  => false,
                            'is_filled'                  => false,
                            'is_animated'                => false,
                            'is_light_fx'                => false,
                            'is_color_icon'              => true,
                            'is_card_filled'             => false,
                            'is_content_center'          => false,
                            'is_heading_active'          => true,
                            'is_filled_inverted'         => false,
                            'is_section_filled_inverted' => true,
                            'is_border'                  => true,
                            'with_padding'               => false,
                            'features'                   => [
                                [
                                    'icon'          => 'sparkles-outline',
                                    'title'         => 'Juno Theme <span class="saturn-tag">New</span>',
                                    'description'   => 'Juno is a new theme for Warriorfolio. It is a modern and intuitive theme that allows you to manage your website and projects easily. With Github Profile integration, you can display your Github repositories on your website.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'logo-github',
                                    'title'         => 'Github Module <span class="saturn-tag">New</span>',
                                    'description'   => 'The Github Module is a new feature that allows you to display your Github repositories on your website. You can also display your Github profile and your latest commits.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'color-wand-outline',
                                    'title'         => 'QuickAccess <span class="saturn-tag">New</span>',
                                    'description'   => 'QuickAccess is a new feature that allows you to access your most used components quickly. You can add your favorite components to QuickAccess and access them easily from anywhere in the application.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'planet-outline',
                                    'title'         => 'Saturn UI  <span class="saturn-tag">Updated</span> ',
                                    'description'   => 'Saturn UI is a new design system that provides a modern and intuitive interface for your website. It is based on the latest web technologies and provides a solid foundation for your website.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'chatbox-outline',
                                    'title'         => 'Notes (Blog) <span class="saturn-tag">Updated</span>',
                                    'description'   => 'The Notes module is a blog where you can write your ideas, thoughts and share your knowledge with the world. You can create categories, tags and share your notes with your visitors.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'logo-whatsapp',
                                    'title'         => 'Whatsapp Web Chatbox <span class="saturn-tag">Updated</span>',
                                    'description'   => 'You can display a whatsapp web button on your website. This feature is hidden and can be activated in the settings.Works on mobile and desktop.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'document-outline',
                                    'title'         => 'Pages <span class="saturn-tag">Updated</span>',
                                    'description'   => 'You can create as many pages as you want and, following the concept of modularity, add pre-built components to them or create your own through components that combine with each other.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'rocket-outline',
                                    'title'         => 'Portfolio Showcase <span class="saturn-tag">Updated</span>',
                                    'description'   => 'Insert your recent projects, add tags, categories and display them to your visitors in a practical and fast way. Your work is displayed in a gallery of up to 12 components.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'albums-outline',
                                    'title'         => 'Sliders',
                                    'description'   => 'Create sliders with images, videos and text. You can use them in your projects, in the Hero Section or in any other part of your website. The sliders are fully customizable.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'hardware-chip-outline',
                                    'title'         => 'Core Modules <span class="saturn-tag">Updated</span>',
                                    'description'   => 'These are pre-build components that cannot be changed individually. This is designed to accelerate the development of new pages. Through these modules, you have access to several specific functionalities.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'flash-outline',
                                    'title'         => 'Hero Section <span class="saturn-tag">Updated</span>',
                                    'description'   => 'Improved Hero Section, redesigned layout, more intuitive to use. It now comes with Sierra, a new interface with new presentation possibilities. Enchant your visitors from the first moment.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon' => 'heart-outline',
                                    'title'
                                                    => 'Sidebar',
                                    'description'   => 'Smarter Sidebar with main elements accessible for easy location. Don\'t waste your time looking for the number of unread messages, for example, just look at the badge on your sidebar.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'terminal-outline',
                                    'title'         => 'Hackable Fields',
                                    'description'   => 'Have total control of your application. Smart shortcuts, functions distributed throughout the system for you to customize the layout of your application as you wish. Use special CSS classes like "tl" for text effects or "saturn-tag" to create an animated tag.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'mail-outline',
                                    'title'         => 'Messages',
                                    'description'   => 'Receive messages and in the future, write, through a modern Inbox with advanced filters. Received, sent, favorite messages in a single inbox, making your day-to-day easier.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'leaf-outline',
                                    'title'         => 'Boost',
                                    'description'   => 'The layout of the entire system, both your Dashboard and the Website, have been redesigned. Incredible performance gain, with a huge evolution in Laravel Queries and also in System Architecture.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'telescope-outline',
                                    'title'         => 'Activity Log',
                                    'description'   => 'The Activity Log is a new feature that allows you to track all the actions performed in your application. You can see who did what and when, making it easier to manage your website and projects.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                            ],
                        ],
                    ],
                    [
                        'type' => 'component.feature-list',
                        'data' => [
                            'module_title'               => 'Core Components',
                            'module_subtitle'            => 'Now that you know some of the main features and updates in this version of Warriorfolio.',
                            'columns'                    => '4',
                            'is_active'                  => true,
                            'is_center'                  => false,
                            'is_filled'                  => false,
                            'is_animated'                => false,
                            'is_light_fx'                => false,
                            'is_color_icon'              => false,
                            'is_card_filled'             => false,
                            'is_content_center'          => false,
                            'is_heading_active'          => true,
                            'is_filled_inverted'         => false,
                            'is_section_filled_inverted' => false,
                            'is_border'                  => true,
                            'with_padding'               => false,
                            'features'                   => [
                                [
                                    'icon'          => 'pencil-outline',
                                    'title'         => 'Notes',
                                    'description'   => 'The Notes module is a blog where you can write your ideas, thoughts and share your knowledge with the world. You can create categories, tags and share your notes with your visitors.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'menu-outline',
                                    'title'         => 'Header',
                                    'description'   => 'The Header is responsible for the entire top of your application. Where you can add links to your social networks, logo, search bar and other important links.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'flash-outline',
                                    'title'         => 'Hero Section',
                                    'description'   => 'The Hero Section is the first section of your application. It is responsible for displaying the main information of your website, such as the title, subtitle and a call to action. It is a great way to introduce your website to your visitors.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'images-outline',
                                    'title'         => 'Projects Section',
                                    'description'   => 'This section is responsible for displaying your projects. It is a gallery of up to 12 projects, where you can add images, videos and text. You can also add tags and categories to your projects.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'person-outline',
                                    'title'         => 'Profile Section',
                                    'description'   => 'This section is responsible for displaying your profile. You can add your name, photo, description and social networks. It is a great way to introduce yourself to your visitors.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'mail-open-outline',
                                    'title'         => 'Mailing List Module',
                                    'description'   => 'Module responsible for capturing emails for your Mailing List. You can export this data through the CSV format and use it in other message sending services.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'chatbubbles-outline',
                                    'title'         => 'Contact Section',
                                    'description'   => 'This section is responsible for displaying your contact information. You can add your email, phone number, address and social networks. It is a great way to let your visitors know how to contact you.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                                [
                                    'icon'          => 'grid-outline',
                                    'title'         => 'Footer Section',
                                    'description'   => 'The Footer is responsible for the entire bottom of your application. Where you can add links to your social networks, copyright information and other important links.',
                                    'link'          => null,
                                    'is_new_window' => false,
                                ],
                            ],
                        ],
                    ],
                    [
                        'type' => 'component.feature-list',
                        'data' => [
                            'module_title'               => 'More Information',
                            'module_subtitle'            => 'Stay connected with Warriorfolio',
                            'columns'                    => 3,
                            'is_active'                  => true,
                            'is_center'                  => false,
                            'is_filled'                  => false,
                            'is_animated'                => false,
                            'is_light_fx'                => true,
                            'is_color_icon'              => false,
                            'is_card_filled'             => true,
                            'is_content_center'          => false,
                            'is_heading_active'          => true,
                            'is_filled_inverted'         => false,
                            'is_section_filled_inverted' => false,
                            'is_border'                  => true,
                            'with_padding'               => false,
                            'features'                   => [
                                [
                                    'icon'          => 'logo-vercel',
                                    'title'         => 'Official Documentation',
                                    'description'   => 'The official documentation on Vercel.',
                                    'link'          => 'https://warriorfolio.vercel.app',
                                    'is_new_window' => true,
                                    'role'          => 'primary',
                                ],
                                [
                                    'icon'          => 'logo-github',
                                    'title'         => 'Github Repository',
                                    'description'   => 'Get the latest updates on Github ',
                                    'link'          => 'https://github.com/mviniciusca/warriorfolio',
                                    'is_new_window' => true,
                                    'role'          => 'info',
                                ],
                                [
                                    'icon'          => 'logo-laravel',
                                    'title'         => 'Laravel Community ',
                                    'description'   => 'Get the latest updates on Github ',
                                    'link'          => 'https://laravel.com',
                                    'is_new_window' => true,
                                    'role'          => 'danger',
                                ],
                            ],
                        ],
                    ],
                ]),
            ]);
    }
}
